version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-users_db}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-users_db}
      JWT_SECRET: ${JWT_SECRET:-secret}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
volumes:
  db_data:
  node_modules: